In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('data.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1062989 entries, 0 to 1062988
Data columns (total 10 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   invoice       1062989 non-null  object
 1   stockcode     1062989 non-null  object
 2   description   1062989 non-null  object
 3   quantity      1062989 non-null  int64
 4   invoicedate   1062989 non-null  object
 5   price         1062989 non-null  float64
 6   customer_id   824364 non-null   float64
 7   country       1062989 non-null  object
 8   is_cancelled  1062989 non-null  bool
 9   total_price   1062989 non-null  float64
dtypes: bool(1), float64(3), int64(1), object(5)
memory usage: 74.0+ MB

In [7]:
df.shape

(1062989, 10)

In [8]:
df.isnull().sum()

invoice              0
stockcode            0
description          0
quantity             0
invoicedate          0
price                0
customer_id     238625
country              0
is_cancelled         0
total_price          0
dtype: int64

In [9]:
(df.isnull().sum()/len(df))*100

invoice          0.000000
stockcode        0.000000
description      0.000000
quantity         0.000000
invoicedate      0.000000
price            0.000000
customer_id     22.448492
country          0.000000
is_cancelled     0.000000
total_price      0.000000
dtype: float64

In [10]:
df.duplicated().sum()

np.int64(34228)

In [11]:
df["description"].nunique()

5698

In [12]:
df.describe()

           quantity         price    customer_id   total_price
count  1.062989e+06  1.062989e+06  824364.000000  1.062989e+06
mean   1.005103e+01  4.668554e+00   15324.638504  1.814436e+01
std    1.699307e+02  1.238071e+02    1697.464450  2.930200e+02
min   -8.099500e+04 -5.359436e+04   12346.000000 -1.684696e+05
25%    1.000000e+00  1.250000e+00   13975.000000  3.750000e+00
50%    3.000000e+00  2.100000e+00   15255.000000  9.900000e+00
75%    1.000000e+01  4.150000e+00   16797.000000  1.770000e+01
max    8.099500e+04  3.897000e+04   18287.000000  1.684696e+05

In [13]:
df["is_cancelled"].value_counts()

is_cancelled
False    1043495
True       19494
Name: count, dtype: int64

In [14]:
df["invoicedate"] = pd.to_datetime(df["invoicedate"])

In [16]:
df["invoicedate"] = pd.to_datetime(df["invoicedate"])

In [17]:
df = df.dropna(subset=["customer_id"])

In [18]:
df = df.drop_duplicates()

In [19]:
df = df[df["is_cancelled"] == False]

In [20]:
(df["quantity"] <= 0).sum()

np.int64(0)

In [21]:
(df["price"] <= 0).sum()

np.int64(70)

In [22]:
print(df["invoicedate"].min())
print(df["invoicedate"].max())

2009-12-01 07:45:00
2011-12-09 12:50:00

In [23]:
# Step 1
df["invoicedate"] = pd.to_datetime(df["invoicedate"])

# Step 2
df = df.drop_duplicates()

# Step 3
df = df.dropna(subset=["customer_id"])

# Step 4
df = df[df["is_cancelled"] == False]

# Step 5
df = df[df["quantity"] > 0]

# Step 6
df = df[df["price"] > 0]

# Step 7
df["customer_id"] = df["customer_id"].astype("int64")

# Step 8
df.to_csv("clean_data.csv", index=False)

In [ ]:
df.shape

(779425, 10)

In [29]:
# Convert invoice date
df["invoicedate"] = pd.to_datetime(df["invoicedate"])

# Remove duplicate rows
df = df.drop_duplicates()

# Remove missing customer IDs
df = df.dropna(subset=["customer_id"])

# Remove cancelled orders
df = df[df["is_cancelled"] == False]

# Remove zero-priced items
df = df[df["price"] > 0]

# Convert customer ID to integer
df["customer_id"] = df["customer_id"].astype("int64")

In [30]:
df["customer_id"].nunique()

5878

In [31]:
df.to_csv("clean_data.csv", index=False)

In [32]:
print(df.shape)

print(df.isnull().sum())

print(df.duplicated().sum())

print(df["customer_id"].nunique())

(779425, 10)
invoice         0
stockcode       0
description     0
quantity        0
invoicedate     0
price           0
customer_id     0
country         0
is_cancelled    0
total_price     0
dtype: int64
0
5878

In [33]:
df["Year"] = df["invoicedate"].dt.year

df["Month"] = df["invoicedate"].dt.month

df["Month_Name"] = df["invoicedate"].dt.month_name()

df["Quarter"] = df["invoicedate"].dt.quarter

df["Weekday"] = df["invoicedate"].dt.day_name()

df["Hour"] = df["invoicedate"].dt.hour

In [34]:
df.head()

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country,is_cancelled,total_price,Year,Month,Month_Name,Quarter,Weekday,Hour
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,False,83.4,2009,12,December,4,Tuesday,7
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,False,81.0,2009,12,December,4,Tuesday,7
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,False,81.0,2009,12,December,4,Tuesday,7
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,False,100.8,2009,12,December,4,Tuesday,7
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,False,30.0,2009,12,December,4,Tuesday,7